name: flutter_application_2
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^10.0.6
  firebase_core: ^2.3.0
  firebase_auth: ^4.2.5
  cached_network_image: ^3.2.3
  wave: ^0.2.2
  curved_navigation_bar: ^1.0.3
  http: ^1.1.0
  sleek_circular_slider: ^2.0.1
  animated_bottom_navigation_bar: ^1.2.0
  page_transition: ^2.0.9
  syncfusion_flutter_charts: ^22.1.39
  syncfusion_flutter_datagrid: ^22.1.39
  avatar_glow: ^2.0.2
  speech_to_text: ^6.3.0
  percent_indicator: ^4.2.3 # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Icon/iconAppbar.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/imagedoan.jpg
    - images/ICON/Chart.png
    - images/ICON/LOGO_UTH.png
    - images/ICON/pump.png
    - images/ICON/lampOn.png
    - images/ICON/Fan.png
    - images/ICON/roof.png
    - images/ICON/reset.png
    - images/ICON/Tick-green.png
    - images/ICON/Tick-red.png
    - images/ICON/Auto.png
    - images/ICON/Led-OFF.png
    - images/ICON/Pump-OFF.png
    - images/ICON/Fan-OFF.png
    - images/ICON/Roof-OFF.png
    - images/ICON/Reset-ON.png
    - images/ICON/Reset_OFF.png
    - images/ICON/Customer.png
    - images/ICON/Auto.png
    - images/ICON/Manual.png
    - images/ICON/temp.png
    - images/ICON/soil.png
    - images/ICON/humi.png
    - images/ICON/lux.png
    - images/ICON/weather.png
    - images/ICON/Rain.png
    - images/ICON/Sunny.png
    - images/ICON/GMT.png
    - images/ICON/iconAppbar.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
